
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Task` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Task
 * 
 */
export type TaskModel = runtime.Types.Result.DefaultSelection<Prisma.$TaskPayload>

export type AggregateTask = {
  _count: TaskCountAggregateOutputType | null
  _avg: TaskAvgAggregateOutputType | null
  _sum: TaskSumAggregateOutputType | null
  _min: TaskMinAggregateOutputType | null
  _max: TaskMaxAggregateOutputType | null
}

export type TaskAvgAggregateOutputType = {
  id: number | null
  recurringInterval: number | null
  listId: number | null
}

export type TaskSumAggregateOutputType = {
  id: number | null
  recurringInterval: number | null
  listId: number | null
}

export type TaskMinAggregateOutputType = {
  id: number | null
  title: string | null
  description: string | null
  status: $Enums.TaskStatus | null
  priority: $Enums.Priority | null
  dueDate: Date | null
  deadline: Date | null
  estimate: string | null
  actual: string | null
  recurringEnabled: boolean | null
  recurringFrequency: string | null
  recurringInterval: number | null
  completedAt: Date | null
  createdAt: Date | null
  updatedAt: Date | null
  listId: number | null
}

export type TaskMaxAggregateOutputType = {
  id: number | null
  title: string | null
  description: string | null
  status: $Enums.TaskStatus | null
  priority: $Enums.Priority | null
  dueDate: Date | null
  deadline: Date | null
  estimate: string | null
  actual: string | null
  recurringEnabled: boolean | null
  recurringFrequency: string | null
  recurringInterval: number | null
  completedAt: Date | null
  createdAt: Date | null
  updatedAt: Date | null
  listId: number | null
}

export type TaskCountAggregateOutputType = {
  id: number
  title: number
  description: number
  status: number
  priority: number
  dueDate: number
  deadline: number
  estimate: number
  actual: number
  recurringEnabled: number
  recurringFrequency: number
  recurringInterval: number
  completedAt: number
  createdAt: number
  updatedAt: number
  listId: number
  _all: number
}


export type TaskAvgAggregateInputType = {
  id?: true
  recurringInterval?: true
  listId?: true
}

export type TaskSumAggregateInputType = {
  id?: true
  recurringInterval?: true
  listId?: true
}

export type TaskMinAggregateInputType = {
  id?: true
  title?: true
  description?: true
  status?: true
  priority?: true
  dueDate?: true
  deadline?: true
  estimate?: true
  actual?: true
  recurringEnabled?: true
  recurringFrequency?: true
  recurringInterval?: true
  completedAt?: true
  createdAt?: true
  updatedAt?: true
  listId?: true
}

export type TaskMaxAggregateInputType = {
  id?: true
  title?: true
  description?: true
  status?: true
  priority?: true
  dueDate?: true
  deadline?: true
  estimate?: true
  actual?: true
  recurringEnabled?: true
  recurringFrequency?: true
  recurringInterval?: true
  completedAt?: true
  createdAt?: true
  updatedAt?: true
  listId?: true
}

export type TaskCountAggregateInputType = {
  id?: true
  title?: true
  description?: true
  status?: true
  priority?: true
  dueDate?: true
  deadline?: true
  estimate?: true
  actual?: true
  recurringEnabled?: true
  recurringFrequency?: true
  recurringInterval?: true
  completedAt?: true
  createdAt?: true
  updatedAt?: true
  listId?: true
  _all?: true
}

export type TaskAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Task to aggregate.
   */
  where?: Prisma.TaskWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Tasks to fetch.
   */
  orderBy?: Prisma.TaskOrderByWithRelationInput | Prisma.TaskOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.TaskWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Tasks from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Tasks.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Tasks
  **/
  _count?: true | TaskCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: TaskAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: TaskSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: TaskMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: TaskMaxAggregateInputType
}

export type GetTaskAggregateType<T extends TaskAggregateArgs> = {
      [P in keyof T & keyof AggregateTask]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateTask[P]>
    : Prisma.GetScalarType<T[P], AggregateTask[P]>
}




export type TaskGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.TaskWhereInput
  orderBy?: Prisma.TaskOrderByWithAggregationInput | Prisma.TaskOrderByWithAggregationInput[]
  by: Prisma.TaskScalarFieldEnum[] | Prisma.TaskScalarFieldEnum
  having?: Prisma.TaskScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: TaskCountAggregateInputType | true
  _avg?: TaskAvgAggregateInputType
  _sum?: TaskSumAggregateInputType
  _min?: TaskMinAggregateInputType
  _max?: TaskMaxAggregateInputType
}

export type TaskGroupByOutputType = {
  id: number
  title: string
  description: string | null
  status: $Enums.TaskStatus
  priority: $Enums.Priority
  dueDate: Date | null
  deadline: Date | null
  estimate: string | null
  actual: string | null
  recurringEnabled: boolean
  recurringFrequency: string | null
  recurringInterval: number | null
  completedAt: Date | null
  createdAt: Date
  updatedAt: Date
  listId: number
  _count: TaskCountAggregateOutputType | null
  _avg: TaskAvgAggregateOutputType | null
  _sum: TaskSumAggregateOutputType | null
  _min: TaskMinAggregateOutputType | null
  _max: TaskMaxAggregateOutputType | null
}

type GetTaskGroupByPayload<T extends TaskGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<TaskGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof TaskGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], TaskGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], TaskGroupByOutputType[P]>
      }
    >
  >



export type TaskWhereInput = {
  AND?: Prisma.TaskWhereInput | Prisma.TaskWhereInput[]
  OR?: Prisma.TaskWhereInput[]
  NOT?: Prisma.TaskWhereInput | Prisma.TaskWhereInput[]
  id?: Prisma.IntFilter<"Task"> | number
  title?: Prisma.StringFilter<"Task"> | string
  description?: Prisma.StringNullableFilter<"Task"> | string | null
  status?: Prisma.EnumTaskStatusFilter<"Task"> | $Enums.TaskStatus
  priority?: Prisma.EnumPriorityFilter<"Task"> | $Enums.Priority
  dueDate?: Prisma.DateTimeNullableFilter<"Task"> | Date | string | null
  deadline?: Prisma.DateTimeNullableFilter<"Task"> | Date | string | null
  estimate?: Prisma.StringNullableFilter<"Task"> | string | null
  actual?: Prisma.StringNullableFilter<"Task"> | string | null
  recurringEnabled?: Prisma.BoolFilter<"Task"> | boolean
  recurringFrequency?: Prisma.StringNullableFilter<"Task"> | string | null
  recurringInterval?: Prisma.IntNullableFilter<"Task"> | number | null
  completedAt?: Prisma.DateTimeNullableFilter<"Task"> | Date | string | null
  createdAt?: Prisma.DateTimeFilter<"Task"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Task"> | Date | string
  listId?: Prisma.IntFilter<"Task"> | number
  list?: Prisma.XOR<Prisma.ListScalarRelationFilter, Prisma.ListWhereInput>
  subtasks?: Prisma.SubtaskListRelationFilter
  reminders?: Prisma.ReminderListRelationFilter
  attachments?: Prisma.AttachmentListRelationFilter
  taskLabels?: Prisma.TaskLabelListRelationFilter
}

export type TaskOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  status?: Prisma.SortOrder
  priority?: Prisma.SortOrder
  dueDate?: Prisma.SortOrderInput | Prisma.SortOrder
  deadline?: Prisma.SortOrderInput | Prisma.SortOrder
  estimate?: Prisma.SortOrderInput | Prisma.SortOrder
  actual?: Prisma.SortOrderInput | Prisma.SortOrder
  recurringEnabled?: Prisma.SortOrder
  recurringFrequency?: Prisma.SortOrderInput | Prisma.SortOrder
  recurringInterval?: Prisma.SortOrderInput | Prisma.SortOrder
  completedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  listId?: Prisma.SortOrder
  list?: Prisma.ListOrderByWithRelationInput
  subtasks?: Prisma.SubtaskOrderByRelationAggregateInput
  reminders?: Prisma.ReminderOrderByRelationAggregateInput
  attachments?: Prisma.AttachmentOrderByRelationAggregateInput
  taskLabels?: Prisma.TaskLabelOrderByRelationAggregateInput
}

export type TaskWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  AND?: Prisma.TaskWhereInput | Prisma.TaskWhereInput[]
  OR?: Prisma.TaskWhereInput[]
  NOT?: Prisma.TaskWhereInput | Prisma.TaskWhereInput[]
  title?: Prisma.StringFilter<"Task"> | string
  description?: Prisma.StringNullableFilter<"Task"> | string | null
  status?: Prisma.EnumTaskStatusFilter<"Task"> | $Enums.TaskStatus
  priority?: Prisma.EnumPriorityFilter<"Task"> | $Enums.Priority
  dueDate?: Prisma.DateTimeNullableFilter<"Task"> | Date | string | null
  deadline?: Prisma.DateTimeNullableFilter<"Task"> | Date | string | null
  estimate?: Prisma.StringNullableFilter<"Task"> | string | null
  actual?: Prisma.StringNullableFilter<"Task"> | string | null
  recurringEnabled?: Prisma.BoolFilter<"Task"> | boolean
  recurringFrequency?: Prisma.StringNullableFilter<"Task"> | string | null
  recurringInterval?: Prisma.IntNullableFilter<"Task"> | number | null
  completedAt?: Prisma.DateTimeNullableFilter<"Task"> | Date | string | null
  createdAt?: Prisma.DateTimeFilter<"Task"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Task"> | Date | string
  listId?: Prisma.IntFilter<"Task"> | number
  list?: Prisma.XOR<Prisma.ListScalarRelationFilter, Prisma.ListWhereInput>
  subtasks?: Prisma.SubtaskListRelationFilter
  reminders?: Prisma.ReminderListRelationFilter
  attachments?: Prisma.AttachmentListRelationFilter
  taskLabels?: Prisma.TaskLabelListRelationFilter
}, "id">

export type TaskOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  status?: Prisma.SortOrder
  priority?: Prisma.SortOrder
  dueDate?: Prisma.SortOrderInput | Prisma.SortOrder
  deadline?: Prisma.SortOrderInput | Prisma.SortOrder
  estimate?: Prisma.SortOrderInput | Prisma.SortOrder
  actual?: Prisma.SortOrderInput | Prisma.SortOrder
  recurringEnabled?: Prisma.SortOrder
  recurringFrequency?: Prisma.SortOrderInput | Prisma.SortOrder
  recurringInterval?: Prisma.SortOrderInput | Prisma.SortOrder
  completedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  listId?: Prisma.SortOrder
  _count?: Prisma.TaskCountOrderByAggregateInput
  _avg?: Prisma.TaskAvgOrderByAggregateInput
  _max?: Prisma.TaskMaxOrderByAggregateInput
  _min?: Prisma.TaskMinOrderByAggregateInput
  _sum?: Prisma.TaskSumOrderByAggregateInput
}

export type TaskScalarWhereWithAggregatesInput = {
  AND?: Prisma.TaskScalarWhereWithAggregatesInput | Prisma.TaskScalarWhereWithAggregatesInput[]
  OR?: Prisma.TaskScalarWhereWithAggregatesInput[]
  NOT?: Prisma.TaskScalarWhereWithAggregatesInput | Prisma.TaskScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"Task"> | number
  title?: Prisma.StringWithAggregatesFilter<"Task"> | string
  description?: Prisma.StringNullableWithAggregatesFilter<"Task"> | string | null
  status?: Prisma.EnumTaskStatusWithAggregatesFilter<"Task"> | $Enums.TaskStatus
  priority?: Prisma.EnumPriorityWithAggregatesFilter<"Task"> | $Enums.Priority
  dueDate?: Prisma.DateTimeNullableWithAggregatesFilter<"Task"> | Date | string | null
  deadline?: Prisma.DateTimeNullableWithAggregatesFilter<"Task"> | Date | string | null
  estimate?: Prisma.StringNullableWithAggregatesFilter<"Task"> | string | null
  actual?: Prisma.StringNullableWithAggregatesFilter<"Task"> | string | null
  recurringEnabled?: Prisma.BoolWithAggregatesFilter<"Task"> | boolean
  recurringFrequency?: Prisma.StringNullableWithAggregatesFilter<"Task"> | string | null
  recurringInterval?: Prisma.IntNullableWithAggregatesFilter<"Task"> | number | null
  completedAt?: Prisma.DateTimeNullableWithAggregatesFilter<"Task"> | Date | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"Task"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"Task"> | Date | string
  listId?: Prisma.IntWithAggregatesFilter<"Task"> | number
}

export type TaskCreateInput = {
  title: string
  description?: string | null
  status?: $Enums.TaskStatus
  priority?: $Enums.Priority
  dueDate?: Date | string | null
  deadline?: Date | string | null
  estimate?: string | null
  actual?: string | null
  recurringEnabled?: boolean
  recurringFrequency?: string | null
  recurringInterval?: number | null
  completedAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  list: Prisma.ListCreateNestedOneWithoutTasksInput
  subtasks?: Prisma.SubtaskCreateNestedManyWithoutTaskInput
  reminders?: Prisma.ReminderCreateNestedManyWithoutTaskInput
  attachments?: Prisma.AttachmentCreateNestedManyWithoutTaskInput
  taskLabels?: Prisma.TaskLabelCreateNestedManyWithoutTaskInput
}

export type TaskUncheckedCreateInput = {
  id?: number
  title: string
  description?: string | null
  status?: $Enums.TaskStatus
  priority?: $Enums.Priority
  dueDate?: Date | string | null
  deadline?: Date | string | null
  estimate?: string | null
  actual?: string | null
  recurringEnabled?: boolean
  recurringFrequency?: string | null
  recurringInterval?: number | null
  completedAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  listId: number
  subtasks?: Prisma.SubtaskUncheckedCreateNestedManyWithoutTaskInput
  reminders?: Prisma.ReminderUncheckedCreateNestedManyWithoutTaskInput
  attachments?: Prisma.AttachmentUncheckedCreateNestedManyWithoutTaskInput
  taskLabels?: Prisma.TaskLabelUncheckedCreateNestedManyWithoutTaskInput
}

export type TaskUpdateInput = {
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.EnumTaskStatusFieldUpdateOperationsInput | $Enums.TaskStatus
  priority?: Prisma.EnumPriorityFieldUpdateOperationsInput | $Enums.Priority
  dueDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  deadline?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  estimate?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  actual?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  recurringEnabled?: Prisma.BoolFieldUpdateOperationsInput | boolean
  recurringFrequency?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  recurringInterval?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  completedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  list?: Prisma.ListUpdateOneRequiredWithoutTasksNestedInput
  subtasks?: Prisma.SubtaskUpdateManyWithoutTaskNestedInput
  reminders?: Prisma.ReminderUpdateManyWithoutTaskNestedInput
  attachments?: Prisma.AttachmentUpdateManyWithoutTaskNestedInput
  taskLabels?: Prisma.TaskLabelUpdateManyWithoutTaskNestedInput
}

export type TaskUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.EnumTaskStatusFieldUpdateOperationsInput | $Enums.TaskStatus
  priority?: Prisma.EnumPriorityFieldUpdateOperationsInput | $Enums.Priority
  dueDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  deadline?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  estimate?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  actual?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  recurringEnabled?: Prisma.BoolFieldUpdateOperationsInput | boolean
  recurringFrequency?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  recurringInterval?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  completedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  listId?: Prisma.IntFieldUpdateOperationsInput | number
  subtasks?: Prisma.SubtaskUncheckedUpdateManyWithoutTaskNestedInput
  reminders?: Prisma.ReminderUncheckedUpdateManyWithoutTaskNestedInput
  attachments?: Prisma.AttachmentUncheckedUpdateManyWithoutTaskNestedInput
  taskLabels?: Prisma.TaskLabelUncheckedUpdateManyWithoutTaskNestedInput
}

export type TaskCreateManyInput = {
  id?: number
  title: string
  description?: string | null
  status?: $Enums.TaskStatus
  priority?: $Enums.Priority
  dueDate?: Date | string | null
  deadline?: Date | string | null
  estimate?: string | null
  actual?: string | null
  recurringEnabled?: boolean
  recurringFrequency?: string | null
  recurringInterval?: number | null
  completedAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  listId: number
}

export type TaskUpdateManyMutationInput = {
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.EnumTaskStatusFieldUpdateOperationsInput | $Enums.TaskStatus
  priority?: Prisma.EnumPriorityFieldUpdateOperationsInput | $Enums.Priority
  dueDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  deadline?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  estimate?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  actual?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  recurringEnabled?: Prisma.BoolFieldUpdateOperationsInput | boolean
  recurringFrequency?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  recurringInterval?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  completedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TaskUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.EnumTaskStatusFieldUpdateOperationsInput | $Enums.TaskStatus
  priority?: Prisma.EnumPriorityFieldUpdateOperationsInput | $Enums.Priority
  dueDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  deadline?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  estimate?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  actual?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  recurringEnabled?: Prisma.BoolFieldUpdateOperationsInput | boolean
  recurringFrequency?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  recurringInterval?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  completedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  listId?: Prisma.IntFieldUpdateOperationsInput | number
}

export type TaskListRelationFilter = {
  every?: Prisma.TaskWhereInput
  some?: Prisma.TaskWhereInput
  none?: Prisma.TaskWhereInput
}

export type TaskOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type TaskCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrder
  status?: Prisma.SortOrder
  priority?: Prisma.SortOrder
  dueDate?: Prisma.SortOrder
  deadline?: Prisma.SortOrder
  estimate?: Prisma.SortOrder
  actual?: Prisma.SortOrder
  recurringEnabled?: Prisma.SortOrder
  recurringFrequency?: Prisma.SortOrder
  recurringInterval?: Prisma.SortOrder
  completedAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  listId?: Prisma.SortOrder
}

export type TaskAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  recurringInterval?: Prisma.SortOrder
  listId?: Prisma.SortOrder
}

export type TaskMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrder
  status?: Prisma.SortOrder
  priority?: Prisma.SortOrder
  dueDate?: Prisma.SortOrder
  deadline?: Prisma.SortOrder
  estimate?: Prisma.SortOrder
  actual?: Prisma.SortOrder
  recurringEnabled?: Prisma.SortOrder
  recurringFrequency?: Prisma.SortOrder
  recurringInterval?: Prisma.SortOrder
  completedAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  listId?: Prisma.SortOrder
}

export type TaskMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrder
  status?: Prisma.SortOrder
  priority?: Prisma.SortOrder
  dueDate?: Prisma.SortOrder
  deadline?: Prisma.SortOrder
  estimate?: Prisma.SortOrder
  actual?: Prisma.SortOrder
  recurringEnabled?: Prisma.SortOrder
  recurringFrequency?: Prisma.SortOrder
  recurringInterval?: Prisma.SortOrder
  completedAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  listId?: Prisma.SortOrder
}

export type TaskSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  recurringInterval?: Prisma.SortOrder
  listId?: Prisma.SortOrder
}

export type TaskScalarRelationFilter = {
  is?: Prisma.TaskWhereInput
  isNot?: Prisma.TaskWhereInput
}

export type TaskCreateNestedManyWithoutListInput = {
  create?: Prisma.XOR<Prisma.TaskCreateWithoutListInput, Prisma.TaskUncheckedCreateWithoutListInput> | Prisma.TaskCreateWithoutListInput[] | Prisma.TaskUncheckedCreateWithoutListInput[]
  connectOrCreate?: Prisma.TaskCreateOrConnectWithoutListInput | Prisma.TaskCreateOrConnectWithoutListInput[]
  createMany?: Prisma.TaskCreateManyListInputEnvelope
  connect?: Prisma.TaskWhereUniqueInput | Prisma.TaskWhereUniqueInput[]
}

export type TaskUncheckedCreateNestedManyWithoutListInput = {
  create?: Prisma.XOR<Prisma.TaskCreateWithoutListInput, Prisma.TaskUncheckedCreateWithoutListInput> | Prisma.TaskCreateWithoutListInput[] | Prisma.TaskUncheckedCreateWithoutListInput[]
  connectOrCreate?: Prisma.TaskCreateOrConnectWithoutListInput | Prisma.TaskCreateOrConnectWithoutListInput[]
  createMany?: Prisma.TaskCreateManyListInputEnvelope
  connect?: Prisma.TaskWhereUniqueInput | Prisma.TaskWhereUniqueInput[]
}

export type TaskUpdateManyWithoutListNestedInput = {
  create?: Prisma.XOR<Prisma.TaskCreateWithoutListInput, Prisma.TaskUncheckedCreateWithoutListInput> | Prisma.TaskCreateWithoutListInput[] | Prisma.TaskUncheckedCreateWithoutListInput[]
  connectOrCreate?: Prisma.TaskCreateOrConnectWithoutListInput | Prisma.TaskCreateOrConnectWithoutListInput[]
  upsert?: Prisma.TaskUpsertWithWhereUniqueWithoutListInput | Prisma.TaskUpsertWithWhereUniqueWithoutListInput[]
  createMany?: Prisma.TaskCreateManyListInputEnvelope
  set?: Prisma.TaskWhereUniqueInput | Prisma.TaskWhereUniqueInput[]
  disconnect?: Prisma.TaskWhereUniqueInput | Prisma.TaskWhereUniqueInput[]
  delete?: Prisma.TaskWhereUniqueInput | Prisma.TaskWhereUniqueInput[]
  connect?: Prisma.TaskWhereUniqueInput | Prisma.TaskWhereUniqueInput[]
  update?: Prisma.TaskUpdateWithWhereUniqueWithoutListInput | Prisma.TaskUpdateWithWhereUniqueWithoutListInput[]
  updateMany?: Prisma.TaskUpdateManyWithWhereWithoutListInput | Prisma.TaskUpdateManyWithWhereWithoutListInput[]
  deleteMany?: Prisma.TaskScalarWhereInput | Prisma.TaskScalarWhereInput[]
}

export type TaskUncheckedUpdateManyWithoutListNestedInput = {
  create?: Prisma.XOR<Prisma.TaskCreateWithoutListInput, Prisma.TaskUncheckedCreateWithoutListInput> | Prisma.TaskCreateWithoutListInput[] | Prisma.TaskUncheckedCreateWithoutListInput[]
  connectOrCreate?: Prisma.TaskCreateOrConnectWithoutListInput | Prisma.TaskCreateOrConnectWithoutListInput[]
  upsert?: Prisma.TaskUpsertWithWhereUniqueWithoutListInput | Prisma.TaskUpsertWithWhereUniqueWithoutListInput[]
  createMany?: Prisma.TaskCreateManyListInputEnvelope
  set?: Prisma.TaskWhereUniqueInput | Prisma.TaskWhereUniqueInput[]
  disconnect?: Prisma.TaskWhereUniqueInput | Prisma.TaskWhereUniqueInput[]
  delete?: Prisma.TaskWhereUniqueInput | Prisma.TaskWhereUniqueInput[]
  connect?: Prisma.TaskWhereUniqueInput | Prisma.TaskWhereUniqueInput[]
  update?: Prisma.TaskUpdateWithWhereUniqueWithoutListInput | Prisma.TaskUpdateWithWhereUniqueWithoutListInput[]
  updateMany?: Prisma.TaskUpdateManyWithWhereWithoutListInput | Prisma.TaskUpdateManyWithWhereWithoutListInput[]
  deleteMany?: Prisma.TaskScalarWhereInput | Prisma.TaskScalarWhereInput[]
}

export type EnumTaskStatusFieldUpdateOperationsInput = {
  set?: $Enums.TaskStatus
}

export type EnumPriorityFieldUpdateOperationsInput = {
  set?: $Enums.Priority
}

export type NullableDateTimeFieldUpdateOperationsInput = {
  set?: Date | string | null
}

export type NullableIntFieldUpdateOperationsInput = {
  set?: number | null
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type TaskCreateNestedOneWithoutSubtasksInput = {
  create?: Prisma.XOR<Prisma.TaskCreateWithoutSubtasksInput, Prisma.TaskUncheckedCreateWithoutSubtasksInput>
  connectOrCreate?: Prisma.TaskCreateOrConnectWithoutSubtasksInput
  connect?: Prisma.TaskWhereUniqueInput
}

export type TaskUpdateOneRequiredWithoutSubtasksNestedInput = {
  create?: Prisma.XOR<Prisma.TaskCreateWithoutSubtasksInput, Prisma.TaskUncheckedCreateWithoutSubtasksInput>
  connectOrCreate?: Prisma.TaskCreateOrConnectWithoutSubtasksInput
  upsert?: Prisma.TaskUpsertWithoutSubtasksInput
  connect?: Prisma.TaskWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.TaskUpdateToOneWithWhereWithoutSubtasksInput, Prisma.TaskUpdateWithoutSubtasksInput>, Prisma.TaskUncheckedUpdateWithoutSubtasksInput>
}

export type TaskCreateNestedOneWithoutRemindersInput = {
  create?: Prisma.XOR<Prisma.TaskCreateWithoutRemindersInput, Prisma.TaskUncheckedCreateWithoutRemindersInput>
  connectOrCreate?: Prisma.TaskCreateOrConnectWithoutRemindersInput
  connect?: Prisma.TaskWhereUniqueInput
}

export type TaskUpdateOneRequiredWithoutRemindersNestedInput = {
  create?: Prisma.XOR<Prisma.TaskCreateWithoutRemindersInput, Prisma.TaskUncheckedCreateWithoutRemindersInput>
  connectOrCreate?: Prisma.TaskCreateOrConnectWithoutRemindersInput
  upsert?: Prisma.TaskUpsertWithoutRemindersInput
  connect?: Prisma.TaskWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.TaskUpdateToOneWithWhereWithoutRemindersInput, Prisma.TaskUpdateWithoutRemindersInput>, Prisma.TaskUncheckedUpdateWithoutRemindersInput>
}

export type TaskCreateNestedOneWithoutAttachmentsInput = {
  create?: Prisma.XOR<Prisma.TaskCreateWithoutAttachmentsInput, Prisma.TaskUncheckedCreateWithoutAttachmentsInput>
  connectOrCreate?: Prisma.TaskCreateOrConnectWithoutAttachmentsInput
  connect?: Prisma.TaskWhereUniqueInput
}

export type TaskUpdateOneRequiredWithoutAttachmentsNestedInput = {
  create?: Prisma.XOR<Prisma.TaskCreateWithoutAttachmentsInput, Prisma.TaskUncheckedCreateWithoutAttachmentsInput>
  connectOrCreate?: Prisma.TaskCreateOrConnectWithoutAttachmentsInput
  upsert?: Prisma.TaskUpsertWithoutAttachmentsInput
  connect?: Prisma.TaskWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.TaskUpdateToOneWithWhereWithoutAttachmentsInput, Prisma.TaskUpdateWithoutAttachmentsInput>, Prisma.TaskUncheckedUpdateWithoutAttachmentsInput>
}

export type TaskCreateNestedOneWithoutTaskLabelsInput = {
  create?: Prisma.XOR<Prisma.TaskCreateWithoutTaskLabelsInput, Prisma.TaskUncheckedCreateWithoutTaskLabelsInput>
  connectOrCreate?: Prisma.TaskCreateOrConnectWithoutTaskLabelsInput
  connect?: Prisma.TaskWhereUniqueInput
}

export type TaskUpdateOneRequiredWithoutTaskLabelsNestedInput = {
  create?: Prisma.XOR<Prisma.TaskCreateWithoutTaskLabelsInput, Prisma.TaskUncheckedCreateWithoutTaskLabelsInput>
  connectOrCreate?: Prisma.TaskCreateOrConnectWithoutTaskLabelsInput
  upsert?: Prisma.TaskUpsertWithoutTaskLabelsInput
  connect?: Prisma.TaskWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.TaskUpdateToOneWithWhereWithoutTaskLabelsInput, Prisma.TaskUpdateWithoutTaskLabelsInput>, Prisma.TaskUncheckedUpdateWithoutTaskLabelsInput>
}

export type TaskCreateWithoutListInput = {
  title: string
  description?: string | null
  status?: $Enums.TaskStatus
  priority?: $Enums.Priority
  dueDate?: Date | string | null
  deadline?: Date | string | null
  estimate?: string | null
  actual?: string | null
  recurringEnabled?: boolean
  recurringFrequency?: string | null
  recurringInterval?: number | null
  completedAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  subtasks?: Prisma.SubtaskCreateNestedManyWithoutTaskInput
  reminders?: Prisma.ReminderCreateNestedManyWithoutTaskInput
  attachments?: Prisma.AttachmentCreateNestedManyWithoutTaskInput
  taskLabels?: Prisma.TaskLabelCreateNestedManyWithoutTaskInput
}

export type TaskUncheckedCreateWithoutListInput = {
  id?: number
  title: string
  description?: string | null
  status?: $Enums.TaskStatus
  priority?: $Enums.Priority
  dueDate?: Date | string | null
  deadline?: Date | string | null
  estimate?: string | null
  actual?: string | null
  recurringEnabled?: boolean
  recurringFrequency?: string | null
  recurringInterval?: number | null
  completedAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  subtasks?: Prisma.SubtaskUncheckedCreateNestedManyWithoutTaskInput
  reminders?: Prisma.ReminderUncheckedCreateNestedManyWithoutTaskInput
  attachments?: Prisma.AttachmentUncheckedCreateNestedManyWithoutTaskInput
  taskLabels?: Prisma.TaskLabelUncheckedCreateNestedManyWithoutTaskInput
}

export type TaskCreateOrConnectWithoutListInput = {
  where: Prisma.TaskWhereUniqueInput
  create: Prisma.XOR<Prisma.TaskCreateWithoutListInput, Prisma.TaskUncheckedCreateWithoutListInput>
}

export type TaskCreateManyListInputEnvelope = {
  data: Prisma.TaskCreateManyListInput | Prisma.TaskCreateManyListInput[]
}

export type TaskUpsertWithWhereUniqueWithoutListInput = {
  where: Prisma.TaskWhereUniqueInput
  update: Prisma.XOR<Prisma.TaskUpdateWithoutListInput, Prisma.TaskUncheckedUpdateWithoutListInput>
  create: Prisma.XOR<Prisma.TaskCreateWithoutListInput, Prisma.TaskUncheckedCreateWithoutListInput>
}

export type TaskUpdateWithWhereUniqueWithoutListInput = {
  where: Prisma.TaskWhereUniqueInput
  data: Prisma.XOR<Prisma.TaskUpdateWithoutListInput, Prisma.TaskUncheckedUpdateWithoutListInput>
}

export type TaskUpdateManyWithWhereWithoutListInput = {
  where: Prisma.TaskScalarWhereInput
  data: Prisma.XOR<Prisma.TaskUpdateManyMutationInput, Prisma.TaskUncheckedUpdateManyWithoutListInput>
}

export type TaskScalarWhereInput = {
  AND?: Prisma.TaskScalarWhereInput | Prisma.TaskScalarWhereInput[]
  OR?: Prisma.TaskScalarWhereInput[]
  NOT?: Prisma.TaskScalarWhereInput | Prisma.TaskScalarWhereInput[]
  id?: Prisma.IntFilter<"Task"> | number
  title?: Prisma.StringFilter<"Task"> | string
  description?: Prisma.StringNullableFilter<"Task"> | string | null
  status?: Prisma.EnumTaskStatusFilter<"Task"> | $Enums.TaskStatus
  priority?: Prisma.EnumPriorityFilter<"Task"> | $Enums.Priority
  dueDate?: Prisma.DateTimeNullableFilter<"Task"> | Date | string | null
  deadline?: Prisma.DateTimeNullableFilter<"Task"> | Date | string | null
  estimate?: Prisma.StringNullableFilter<"Task"> | string | null
  actual?: Prisma.StringNullableFilter<"Task"> | string | null
  recurringEnabled?: Prisma.BoolFilter<"Task"> | boolean
  recurringFrequency?: Prisma.StringNullableFilter<"Task"> | string | null
  recurringInterval?: Prisma.IntNullableFilter<"Task"> | number | null
  completedAt?: Prisma.DateTimeNullableFilter<"Task"> | Date | string | null
  createdAt?: Prisma.DateTimeFilter<"Task"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Task"> | Date | string
  listId?: Prisma.IntFilter<"Task"> | number
}

export type TaskCreateWithoutSubtasksInput = {
  title: string
  description?: string | null
  status?: $Enums.TaskStatus
  priority?: $Enums.Priority
  dueDate?: Date | string | null
  deadline?: Date | string | null
  estimate?: string | null
  actual?: string | null
  recurringEnabled?: boolean
  recurringFrequency?: string | null
  recurringInterval?: number | null
  completedAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  list: Prisma.ListCreateNestedOneWithoutTasksInput
  reminders?: Prisma.ReminderCreateNestedManyWithoutTaskInput
  attachments?: Prisma.AttachmentCreateNestedManyWithoutTaskInput
  taskLabels?: Prisma.TaskLabelCreateNestedManyWithoutTaskInput
}

export type TaskUncheckedCreateWithoutSubtasksInput = {
  id?: number
  title: string
  description?: string | null
  status?: $Enums.TaskStatus
  priority?: $Enums.Priority
  dueDate?: Date | string | null
  deadline?: Date | string | null
  estimate?: string | null
  actual?: string | null
  recurringEnabled?: boolean
  recurringFrequency?: string | null
  recurringInterval?: number | null
  completedAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  listId: number
  reminders?: Prisma.ReminderUncheckedCreateNestedManyWithoutTaskInput
  attachments?: Prisma.AttachmentUncheckedCreateNestedManyWithoutTaskInput
  taskLabels?: Prisma.TaskLabelUncheckedCreateNestedManyWithoutTaskInput
}

export type TaskCreateOrConnectWithoutSubtasksInput = {
  where: Prisma.TaskWhereUniqueInput
  create: Prisma.XOR<Prisma.TaskCreateWithoutSubtasksInput, Prisma.TaskUncheckedCreateWithoutSubtasksInput>
}

export type TaskUpsertWithoutSubtasksInput = {
  update: Prisma.XOR<Prisma.TaskUpdateWithoutSubtasksInput, Prisma.TaskUncheckedUpdateWithoutSubtasksInput>
  create: Prisma.XOR<Prisma.TaskCreateWithoutSubtasksInput, Prisma.TaskUncheckedCreateWithoutSubtasksInput>
  where?: Prisma.TaskWhereInput
}

export type TaskUpdateToOneWithWhereWithoutSubtasksInput = {
  where?: Prisma.TaskWhereInput
  data: Prisma.XOR<Prisma.TaskUpdateWithoutSubtasksInput, Prisma.TaskUncheckedUpdateWithoutSubtasksInput>
}

export type TaskUpdateWithoutSubtasksInput = {
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.EnumTaskStatusFieldUpdateOperationsInput | $Enums.TaskStatus
  priority?: Prisma.EnumPriorityFieldUpdateOperationsInput | $Enums.Priority
  dueDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  deadline?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  estimate?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  actual?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  recurringEnabled?: Prisma.BoolFieldUpdateOperationsInput | boolean
  recurringFrequency?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  recurringInterval?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  completedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  list?: Prisma.ListUpdateOneRequiredWithoutTasksNestedInput
  reminders?: Prisma.ReminderUpdateManyWithoutTaskNestedInput
  attachments?: Prisma.AttachmentUpdateManyWithoutTaskNestedInput
  taskLabels?: Prisma.TaskLabelUpdateManyWithoutTaskNestedInput
}

export type TaskUncheckedUpdateWithoutSubtasksInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.EnumTaskStatusFieldUpdateOperationsInput | $Enums.TaskStatus
  priority?: Prisma.EnumPriorityFieldUpdateOperationsInput | $Enums.Priority
  dueDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  deadline?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  estimate?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  actual?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  recurringEnabled?: Prisma.BoolFieldUpdateOperationsInput | boolean
  recurringFrequency?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  recurringInterval?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  completedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  listId?: Prisma.IntFieldUpdateOperationsInput | number
  reminders?: Prisma.ReminderUncheckedUpdateManyWithoutTaskNestedInput
  attachments?: Prisma.AttachmentUncheckedUpdateManyWithoutTaskNestedInput
  taskLabels?: Prisma.TaskLabelUncheckedUpdateManyWithoutTaskNestedInput
}

export type TaskCreateWithoutRemindersInput = {
  title: string
  description?: string | null
  status?: $Enums.TaskStatus
  priority?: $Enums.Priority
  dueDate?: Date | string | null
  deadline?: Date | string | null
  estimate?: string | null
  actual?: string | null
  recurringEnabled?: boolean
  recurringFrequency?: string | null
  recurringInterval?: number | null
  completedAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  list: Prisma.ListCreateNestedOneWithoutTasksInput
  subtasks?: Prisma.SubtaskCreateNestedManyWithoutTaskInput
  attachments?: Prisma.AttachmentCreateNestedManyWithoutTaskInput
  taskLabels?: Prisma.TaskLabelCreateNestedManyWithoutTaskInput
}

export type TaskUncheckedCreateWithoutRemindersInput = {
  id?: number
  title: string
  description?: string | null
  status?: $Enums.TaskStatus
  priority?: $Enums.Priority
  dueDate?: Date | string | null
  deadline?: Date | string | null
  estimate?: string | null
  actual?: string | null
  recurringEnabled?: boolean
  recurringFrequency?: string | null
  recurringInterval?: number | null
  completedAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  listId: number
  subtasks?: Prisma.SubtaskUncheckedCreateNestedManyWithoutTaskInput
  attachments?: Prisma.AttachmentUncheckedCreateNestedManyWithoutTaskInput
  taskLabels?: Prisma.TaskLabelUncheckedCreateNestedManyWithoutTaskInput
}

export type TaskCreateOrConnectWithoutRemindersInput = {
  where: Prisma.TaskWhereUniqueInput
  create: Prisma.XOR<Prisma.TaskCreateWithoutRemindersInput, Prisma.TaskUncheckedCreateWithoutRemindersInput>
}

export type TaskUpsertWithoutRemindersInput = {
  update: Prisma.XOR<Prisma.TaskUpdateWithoutRemindersInput, Prisma.TaskUncheckedUpdateWithoutRemindersInput>
  create: Prisma.XOR<Prisma.TaskCreateWithoutRemindersInput, Prisma.TaskUncheckedCreateWithoutRemindersInput>
  where?: Prisma.TaskWhereInput
}

export type TaskUpdateToOneWithWhereWithoutRemindersInput = {
  where?: Prisma.TaskWhereInput
  data: Prisma.XOR<Prisma.TaskUpdateWithoutRemindersInput, Prisma.TaskUncheckedUpdateWithoutRemindersInput>
}

export type TaskUpdateWithoutRemindersInput = {
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.EnumTaskStatusFieldUpdateOperationsInput | $Enums.TaskStatus
  priority?: Prisma.EnumPriorityFieldUpdateOperationsInput | $Enums.Priority
  dueDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  deadline?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  estimate?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  actual?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  recurringEnabled?: Prisma.BoolFieldUpdateOperationsInput | boolean
  recurringFrequency?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  recurringInterval?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  completedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  list?: Prisma.ListUpdateOneRequiredWithoutTasksNestedInput
  subtasks?: Prisma.SubtaskUpdateManyWithoutTaskNestedInput
  attachments?: Prisma.AttachmentUpdateManyWithoutTaskNestedInput
  taskLabels?: Prisma.TaskLabelUpdateManyWithoutTaskNestedInput
}

export type TaskUncheckedUpdateWithoutRemindersInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.EnumTaskStatusFieldUpdateOperationsInput | $Enums.TaskStatus
  priority?: Prisma.EnumPriorityFieldUpdateOperationsInput | $Enums.Priority
  dueDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  deadline?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  estimate?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  actual?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  recurringEnabled?: Prisma.BoolFieldUpdateOperationsInput | boolean
  recurringFrequency?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  recurringInterval?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  completedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  listId?: Prisma.IntFieldUpdateOperationsInput | number
  subtasks?: Prisma.SubtaskUncheckedUpdateManyWithoutTaskNestedInput
  attachments?: Prisma.AttachmentUncheckedUpdateManyWithoutTaskNestedInput
  taskLabels?: Prisma.TaskLabelUncheckedUpdateManyWithoutTaskNestedInput
}

export type TaskCreateWithoutAttachmentsInput = {
  title: string
  description?: string | null
  status?: $Enums.TaskStatus
  priority?: $Enums.Priority
  dueDate?: Date | string | null
  deadline?: Date | string | null
  estimate?: string | null
  actual?: string | null
  recurringEnabled?: boolean
  recurringFrequency?: string | null
  recurringInterval?: number | null
  completedAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  list: Prisma.ListCreateNestedOneWithoutTasksInput
  subtasks?: Prisma.SubtaskCreateNestedManyWithoutTaskInput
  reminders?: Prisma.ReminderCreateNestedManyWithoutTaskInput
  taskLabels?: Prisma.TaskLabelCreateNestedManyWithoutTaskInput
}

export type TaskUncheckedCreateWithoutAttachmentsInput = {
  id?: number
  title: string
  description?: string | null
  status?: $Enums.TaskStatus
  priority?: $Enums.Priority
  dueDate?: Date | string | null
  deadline?: Date | string | null
  estimate?: string | null
  actual?: string | null
  recurringEnabled?: boolean
  recurringFrequency?: string | null
  recurringInterval?: number | null
  completedAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  listId: number
  subtasks?: Prisma.SubtaskUncheckedCreateNestedManyWithoutTaskInput
  reminders?: Prisma.ReminderUncheckedCreateNestedManyWithoutTaskInput
  taskLabels?: Prisma.TaskLabelUncheckedCreateNestedManyWithoutTaskInput
}

export type TaskCreateOrConnectWithoutAttachmentsInput = {
  where: Prisma.TaskWhereUniqueInput
  create: Prisma.XOR<Prisma.TaskCreateWithoutAttachmentsInput, Prisma.TaskUncheckedCreateWithoutAttachmentsInput>
}

export type TaskUpsertWithoutAttachmentsInput = {
  update: Prisma.XOR<Prisma.TaskUpdateWithoutAttachmentsInput, Prisma.TaskUncheckedUpdateWithoutAttachmentsInput>
  create: Prisma.XOR<Prisma.TaskCreateWithoutAttachmentsInput, Prisma.TaskUncheckedCreateWithoutAttachmentsInput>
  where?: Prisma.TaskWhereInput
}

export type TaskUpdateToOneWithWhereWithoutAttachmentsInput = {
  where?: Prisma.TaskWhereInput
  data: Prisma.XOR<Prisma.TaskUpdateWithoutAttachmentsInput, Prisma.TaskUncheckedUpdateWithoutAttachmentsInput>
}

export type TaskUpdateWithoutAttachmentsInput = {
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.EnumTaskStatusFieldUpdateOperationsInput | $Enums.TaskStatus
  priority?: Prisma.EnumPriorityFieldUpdateOperationsInput | $Enums.Priority
  dueDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  deadline?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  estimate?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  actual?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  recurringEnabled?: Prisma.BoolFieldUpdateOperationsInput | boolean
  recurringFrequency?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  recurringInterval?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  completedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  list?: Prisma.ListUpdateOneRequiredWithoutTasksNestedInput
  subtasks?: Prisma.SubtaskUpdateManyWithoutTaskNestedInput
  reminders?: Prisma.ReminderUpdateManyWithoutTaskNestedInput
  taskLabels?: Prisma.TaskLabelUpdateManyWithoutTaskNestedInput
}

export type TaskUncheckedUpdateWithoutAttachmentsInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.EnumTaskStatusFieldUpdateOperationsInput | $Enums.TaskStatus
  priority?: Prisma.EnumPriorityFieldUpdateOperationsInput | $Enums.Priority
  dueDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  deadline?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  estimate?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  actual?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  recurringEnabled?: Prisma.BoolFieldUpdateOperationsInput | boolean
  recurringFrequency?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  recurringInterval?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  completedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  listId?: Prisma.IntFieldUpdateOperationsInput | number
  subtasks?: Prisma.SubtaskUncheckedUpdateManyWithoutTaskNestedInput
  reminders?: Prisma.ReminderUncheckedUpdateManyWithoutTaskNestedInput
  taskLabels?: Prisma.TaskLabelUncheckedUpdateManyWithoutTaskNestedInput
}

export type TaskCreateWithoutTaskLabelsInput = {
  title: string
  description?: string | null
  status?: $Enums.TaskStatus
  priority?: $Enums.Priority
  dueDate?: Date | string | null
  deadline?: Date | string | null
  estimate?: string | null
  actual?: string | null
  recurringEnabled?: boolean
  recurringFrequency?: string | null
  recurringInterval?: number | null
  completedAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  list: Prisma.ListCreateNestedOneWithoutTasksInput
  subtasks?: Prisma.SubtaskCreateNestedManyWithoutTaskInput
  reminders?: Prisma.ReminderCreateNestedManyWithoutTaskInput
  attachments?: Prisma.AttachmentCreateNestedManyWithoutTaskInput
}

export type TaskUncheckedCreateWithoutTaskLabelsInput = {
  id?: number
  title: string
  description?: string | null
  status?: $Enums.TaskStatus
  priority?: $Enums.Priority
  dueDate?: Date | string | null
  deadline?: Date | string | null
  estimate?: string | null
  actual?: string | null
  recurringEnabled?: boolean
  recurringFrequency?: string | null
  recurringInterval?: number | null
  completedAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  listId: number
  subtasks?: Prisma.SubtaskUncheckedCreateNestedManyWithoutTaskInput
  reminders?: Prisma.ReminderUncheckedCreateNestedManyWithoutTaskInput
  attachments?: Prisma.AttachmentUncheckedCreateNestedManyWithoutTaskInput
}

export type TaskCreateOrConnectWithoutTaskLabelsInput = {
  where: Prisma.TaskWhereUniqueInput
  create: Prisma.XOR<Prisma.TaskCreateWithoutTaskLabelsInput, Prisma.TaskUncheckedCreateWithoutTaskLabelsInput>
}

export type TaskUpsertWithoutTaskLabelsInput = {
  update: Prisma.XOR<Prisma.TaskUpdateWithoutTaskLabelsInput, Prisma.TaskUncheckedUpdateWithoutTaskLabelsInput>
  create: Prisma.XOR<Prisma.TaskCreateWithoutTaskLabelsInput, Prisma.TaskUncheckedCreateWithoutTaskLabelsInput>
  where?: Prisma.TaskWhereInput
}

export type TaskUpdateToOneWithWhereWithoutTaskLabelsInput = {
  where?: Prisma.TaskWhereInput
  data: Prisma.XOR<Prisma.TaskUpdateWithoutTaskLabelsInput, Prisma.TaskUncheckedUpdateWithoutTaskLabelsInput>
}

export type TaskUpdateWithoutTaskLabelsInput = {
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.EnumTaskStatusFieldUpdateOperationsInput | $Enums.TaskStatus
  priority?: Prisma.EnumPriorityFieldUpdateOperationsInput | $Enums.Priority
  dueDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  deadline?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  estimate?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  actual?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  recurringEnabled?: Prisma.BoolFieldUpdateOperationsInput | boolean
  recurringFrequency?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  recurringInterval?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  completedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  list?: Prisma.ListUpdateOneRequiredWithoutTasksNestedInput
  subtasks?: Prisma.SubtaskUpdateManyWithoutTaskNestedInput
  reminders?: Prisma.ReminderUpdateManyWithoutTaskNestedInput
  attachments?: Prisma.AttachmentUpdateManyWithoutTaskNestedInput
}

export type TaskUncheckedUpdateWithoutTaskLabelsInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.EnumTaskStatusFieldUpdateOperationsInput | $Enums.TaskStatus
  priority?: Prisma.EnumPriorityFieldUpdateOperationsInput | $Enums.Priority
  dueDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  deadline?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  estimate?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  actual?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  recurringEnabled?: Prisma.BoolFieldUpdateOperationsInput | boolean
  recurringFrequency?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  recurringInterval?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  completedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  listId?: Prisma.IntFieldUpdateOperationsInput | number
  subtasks?: Prisma.SubtaskUncheckedUpdateManyWithoutTaskNestedInput
  reminders?: Prisma.ReminderUncheckedUpdateManyWithoutTaskNestedInput
  attachments?: Prisma.AttachmentUncheckedUpdateManyWithoutTaskNestedInput
}

export type TaskCreateManyListInput = {
  id?: number
  title: string
  description?: string | null
  status?: $Enums.TaskStatus
  priority?: $Enums.Priority
  dueDate?: Date | string | null
  deadline?: Date | string | null
  estimate?: string | null
  actual?: string | null
  recurringEnabled?: boolean
  recurringFrequency?: string | null
  recurringInterval?: number | null
  completedAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type TaskUpdateWithoutListInput = {
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.EnumTaskStatusFieldUpdateOperationsInput | $Enums.TaskStatus
  priority?: Prisma.EnumPriorityFieldUpdateOperationsInput | $Enums.Priority
  dueDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  deadline?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  estimate?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  actual?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  recurringEnabled?: Prisma.BoolFieldUpdateOperationsInput | boolean
  recurringFrequency?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  recurringInterval?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  completedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  subtasks?: Prisma.SubtaskUpdateManyWithoutTaskNestedInput
  reminders?: Prisma.ReminderUpdateManyWithoutTaskNestedInput
  attachments?: Prisma.AttachmentUpdateManyWithoutTaskNestedInput
  taskLabels?: Prisma.TaskLabelUpdateManyWithoutTaskNestedInput
}

export type TaskUncheckedUpdateWithoutListInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.EnumTaskStatusFieldUpdateOperationsInput | $Enums.TaskStatus
  priority?: Prisma.EnumPriorityFieldUpdateOperationsInput | $Enums.Priority
  dueDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  deadline?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  estimate?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  actual?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  recurringEnabled?: Prisma.BoolFieldUpdateOperationsInput | boolean
  recurringFrequency?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  recurringInterval?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  completedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  subtasks?: Prisma.SubtaskUncheckedUpdateManyWithoutTaskNestedInput
  reminders?: Prisma.ReminderUncheckedUpdateManyWithoutTaskNestedInput
  attachments?: Prisma.AttachmentUncheckedUpdateManyWithoutTaskNestedInput
  taskLabels?: Prisma.TaskLabelUncheckedUpdateManyWithoutTaskNestedInput
}

export type TaskUncheckedUpdateManyWithoutListInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.EnumTaskStatusFieldUpdateOperationsInput | $Enums.TaskStatus
  priority?: Prisma.EnumPriorityFieldUpdateOperationsInput | $Enums.Priority
  dueDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  deadline?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  estimate?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  actual?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  recurringEnabled?: Prisma.BoolFieldUpdateOperationsInput | boolean
  recurringFrequency?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  recurringInterval?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  completedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}


/**
 * Count Type TaskCountOutputType
 */

export type TaskCountOutputType = {
  subtasks: number
  reminders: number
  attachments: number
  taskLabels: number
}

export type TaskCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  subtasks?: boolean | TaskCountOutputTypeCountSubtasksArgs
  reminders?: boolean | TaskCountOutputTypeCountRemindersArgs
  attachments?: boolean | TaskCountOutputTypeCountAttachmentsArgs
  taskLabels?: boolean | TaskCountOutputTypeCountTaskLabelsArgs
}

/**
 * TaskCountOutputType without action
 */
export type TaskCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TaskCountOutputType
   */
  select?: Prisma.TaskCountOutputTypeSelect<ExtArgs> | null
}

/**
 * TaskCountOutputType without action
 */
export type TaskCountOutputTypeCountSubtasksArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.SubtaskWhereInput
}

/**
 * TaskCountOutputType without action
 */
export type TaskCountOutputTypeCountRemindersArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ReminderWhereInput
}

/**
 * TaskCountOutputType without action
 */
export type TaskCountOutputTypeCountAttachmentsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.AttachmentWhereInput
}

/**
 * TaskCountOutputType without action
 */
export type TaskCountOutputTypeCountTaskLabelsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.TaskLabelWhereInput
}


export type TaskSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  title?: boolean
  description?: boolean
  status?: boolean
  priority?: boolean
  dueDate?: boolean
  deadline?: boolean
  estimate?: boolean
  actual?: boolean
  recurringEnabled?: boolean
  recurringFrequency?: boolean
  recurringInterval?: boolean
  completedAt?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  listId?: boolean
  list?: boolean | Prisma.ListDefaultArgs<ExtArgs>
  subtasks?: boolean | Prisma.Task$subtasksArgs<ExtArgs>
  reminders?: boolean | Prisma.Task$remindersArgs<ExtArgs>
  attachments?: boolean | Prisma.Task$attachmentsArgs<ExtArgs>
  taskLabels?: boolean | Prisma.Task$taskLabelsArgs<ExtArgs>
  _count?: boolean | Prisma.TaskCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["task"]>

export type TaskSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  title?: boolean
  description?: boolean
  status?: boolean
  priority?: boolean
  dueDate?: boolean
  deadline?: boolean
  estimate?: boolean
  actual?: boolean
  recurringEnabled?: boolean
  recurringFrequency?: boolean
  recurringInterval?: boolean
  completedAt?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  listId?: boolean
  list?: boolean | Prisma.ListDefaultArgs<ExtArgs>
}, ExtArgs["result"]["task"]>

export type TaskSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  title?: boolean
  description?: boolean
  status?: boolean
  priority?: boolean
  dueDate?: boolean
  deadline?: boolean
  estimate?: boolean
  actual?: boolean
  recurringEnabled?: boolean
  recurringFrequency?: boolean
  recurringInterval?: boolean
  completedAt?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  listId?: boolean
  list?: boolean | Prisma.ListDefaultArgs<ExtArgs>
}, ExtArgs["result"]["task"]>

export type TaskSelectScalar = {
  id?: boolean
  title?: boolean
  description?: boolean
  status?: boolean
  priority?: boolean
  dueDate?: boolean
  deadline?: boolean
  estimate?: boolean
  actual?: boolean
  recurringEnabled?: boolean
  recurringFrequency?: boolean
  recurringInterval?: boolean
  completedAt?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  listId?: boolean
}

export type TaskOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "title" | "description" | "status" | "priority" | "dueDate" | "deadline" | "estimate" | "actual" | "recurringEnabled" | "recurringFrequency" | "recurringInterval" | "completedAt" | "createdAt" | "updatedAt" | "listId", ExtArgs["result"]["task"]>
export type TaskInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  list?: boolean | Prisma.ListDefaultArgs<ExtArgs>
  subtasks?: boolean | Prisma.Task$subtasksArgs<ExtArgs>
  reminders?: boolean | Prisma.Task$remindersArgs<ExtArgs>
  attachments?: boolean | Prisma.Task$attachmentsArgs<ExtArgs>
  taskLabels?: boolean | Prisma.Task$taskLabelsArgs<ExtArgs>
  _count?: boolean | Prisma.TaskCountOutputTypeDefaultArgs<ExtArgs>
}
export type TaskIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  list?: boolean | Prisma.ListDefaultArgs<ExtArgs>
}
export type TaskIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  list?: boolean | Prisma.ListDefaultArgs<ExtArgs>
}

export type $TaskPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Task"
  objects: {
    list: Prisma.$ListPayload<ExtArgs>
    subtasks: Prisma.$SubtaskPayload<ExtArgs>[]
    reminders: Prisma.$ReminderPayload<ExtArgs>[]
    attachments: Prisma.$AttachmentPayload<ExtArgs>[]
    taskLabels: Prisma.$TaskLabelPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    title: string
    description: string | null
    status: $Enums.TaskStatus
    priority: $Enums.Priority
    dueDate: Date | null
    deadline: Date | null
    estimate: string | null
    actual: string | null
    recurringEnabled: boolean
    recurringFrequency: string | null
    recurringInterval: number | null
    completedAt: Date | null
    createdAt: Date
    updatedAt: Date
    listId: number
  }, ExtArgs["result"]["task"]>
  composites: {}
}

export type TaskGetPayload<S extends boolean | null | undefined | TaskDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$TaskPayload, S>

export type TaskCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<TaskFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: TaskCountAggregateInputType | true
  }

export interface TaskDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Task'], meta: { name: 'Task' } }
  /**
   * Find zero or one Task that matches the filter.
   * @param {TaskFindUniqueArgs} args - Arguments to find a Task
   * @example
   * // Get one Task
   * const task = await prisma.task.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends TaskFindUniqueArgs>(args: Prisma.SelectSubset<T, TaskFindUniqueArgs<ExtArgs>>): Prisma.Prisma__TaskClient<runtime.Types.Result.GetResult<Prisma.$TaskPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Task that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {TaskFindUniqueOrThrowArgs} args - Arguments to find a Task
   * @example
   * // Get one Task
   * const task = await prisma.task.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends TaskFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, TaskFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__TaskClient<runtime.Types.Result.GetResult<Prisma.$TaskPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Task that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TaskFindFirstArgs} args - Arguments to find a Task
   * @example
   * // Get one Task
   * const task = await prisma.task.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends TaskFindFirstArgs>(args?: Prisma.SelectSubset<T, TaskFindFirstArgs<ExtArgs>>): Prisma.Prisma__TaskClient<runtime.Types.Result.GetResult<Prisma.$TaskPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Task that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TaskFindFirstOrThrowArgs} args - Arguments to find a Task
   * @example
   * // Get one Task
   * const task = await prisma.task.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends TaskFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, TaskFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__TaskClient<runtime.Types.Result.GetResult<Prisma.$TaskPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Tasks that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TaskFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Tasks
   * const tasks = await prisma.task.findMany()
   * 
   * // Get first 10 Tasks
   * const tasks = await prisma.task.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const taskWithIdOnly = await prisma.task.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends TaskFindManyArgs>(args?: Prisma.SelectSubset<T, TaskFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TaskPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Task.
   * @param {TaskCreateArgs} args - Arguments to create a Task.
   * @example
   * // Create one Task
   * const Task = await prisma.task.create({
   *   data: {
   *     // ... data to create a Task
   *   }
   * })
   * 
   */
  create<T extends TaskCreateArgs>(args: Prisma.SelectSubset<T, TaskCreateArgs<ExtArgs>>): Prisma.Prisma__TaskClient<runtime.Types.Result.GetResult<Prisma.$TaskPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Tasks.
   * @param {TaskCreateManyArgs} args - Arguments to create many Tasks.
   * @example
   * // Create many Tasks
   * const task = await prisma.task.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends TaskCreateManyArgs>(args?: Prisma.SelectSubset<T, TaskCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Tasks and returns the data saved in the database.
   * @param {TaskCreateManyAndReturnArgs} args - Arguments to create many Tasks.
   * @example
   * // Create many Tasks
   * const task = await prisma.task.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Tasks and only return the `id`
   * const taskWithIdOnly = await prisma.task.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends TaskCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, TaskCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TaskPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Task.
   * @param {TaskDeleteArgs} args - Arguments to delete one Task.
   * @example
   * // Delete one Task
   * const Task = await prisma.task.delete({
   *   where: {
   *     // ... filter to delete one Task
   *   }
   * })
   * 
   */
  delete<T extends TaskDeleteArgs>(args: Prisma.SelectSubset<T, TaskDeleteArgs<ExtArgs>>): Prisma.Prisma__TaskClient<runtime.Types.Result.GetResult<Prisma.$TaskPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Task.
   * @param {TaskUpdateArgs} args - Arguments to update one Task.
   * @example
   * // Update one Task
   * const task = await prisma.task.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends TaskUpdateArgs>(args: Prisma.SelectSubset<T, TaskUpdateArgs<ExtArgs>>): Prisma.Prisma__TaskClient<runtime.Types.Result.GetResult<Prisma.$TaskPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Tasks.
   * @param {TaskDeleteManyArgs} args - Arguments to filter Tasks to delete.
   * @example
   * // Delete a few Tasks
   * const { count } = await prisma.task.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends TaskDeleteManyArgs>(args?: Prisma.SelectSubset<T, TaskDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Tasks.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TaskUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Tasks
   * const task = await prisma.task.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends TaskUpdateManyArgs>(args: Prisma.SelectSubset<T, TaskUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Tasks and returns the data updated in the database.
   * @param {TaskUpdateManyAndReturnArgs} args - Arguments to update many Tasks.
   * @example
   * // Update many Tasks
   * const task = await prisma.task.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Tasks and only return the `id`
   * const taskWithIdOnly = await prisma.task.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends TaskUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, TaskUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TaskPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Task.
   * @param {TaskUpsertArgs} args - Arguments to update or create a Task.
   * @example
   * // Update or create a Task
   * const task = await prisma.task.upsert({
   *   create: {
   *     // ... data to create a Task
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Task we want to update
   *   }
   * })
   */
  upsert<T extends TaskUpsertArgs>(args: Prisma.SelectSubset<T, TaskUpsertArgs<ExtArgs>>): Prisma.Prisma__TaskClient<runtime.Types.Result.GetResult<Prisma.$TaskPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Tasks.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TaskCountArgs} args - Arguments to filter Tasks to count.
   * @example
   * // Count the number of Tasks
   * const count = await prisma.task.count({
   *   where: {
   *     // ... the filter for the Tasks we want to count
   *   }
   * })
  **/
  count<T extends TaskCountArgs>(
    args?: Prisma.Subset<T, TaskCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], TaskCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Task.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TaskAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends TaskAggregateArgs>(args: Prisma.Subset<T, TaskAggregateArgs>): Prisma.PrismaPromise<GetTaskAggregateType<T>>

  /**
   * Group by Task.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TaskGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends TaskGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: TaskGroupByArgs['orderBy'] }
      : { orderBy?: TaskGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, TaskGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetTaskGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Task model
 */
readonly fields: TaskFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Task.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__TaskClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  list<T extends Prisma.ListDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ListDefaultArgs<ExtArgs>>): Prisma.Prisma__ListClient<runtime.Types.Result.GetResult<Prisma.$ListPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  subtasks<T extends Prisma.Task$subtasksArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Task$subtasksArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SubtaskPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  reminders<T extends Prisma.Task$remindersArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Task$remindersArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ReminderPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  attachments<T extends Prisma.Task$attachmentsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Task$attachmentsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AttachmentPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  taskLabels<T extends Prisma.Task$taskLabelsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Task$taskLabelsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TaskLabelPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Task model
 */
export interface TaskFieldRefs {
  readonly id: Prisma.FieldRef<"Task", 'Int'>
  readonly title: Prisma.FieldRef<"Task", 'String'>
  readonly description: Prisma.FieldRef<"Task", 'String'>
  readonly status: Prisma.FieldRef<"Task", 'TaskStatus'>
  readonly priority: Prisma.FieldRef<"Task", 'Priority'>
  readonly dueDate: Prisma.FieldRef<"Task", 'DateTime'>
  readonly deadline: Prisma.FieldRef<"Task", 'DateTime'>
  readonly estimate: Prisma.FieldRef<"Task", 'String'>
  readonly actual: Prisma.FieldRef<"Task", 'String'>
  readonly recurringEnabled: Prisma.FieldRef<"Task", 'Boolean'>
  readonly recurringFrequency: Prisma.FieldRef<"Task", 'String'>
  readonly recurringInterval: Prisma.FieldRef<"Task", 'Int'>
  readonly completedAt: Prisma.FieldRef<"Task", 'DateTime'>
  readonly createdAt: Prisma.FieldRef<"Task", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"Task", 'DateTime'>
  readonly listId: Prisma.FieldRef<"Task", 'Int'>
}
    

// Custom InputTypes
/**
 * Task findUnique
 */
export type TaskFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Task
   */
  select?: Prisma.TaskSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Task
   */
  omit?: Prisma.TaskOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TaskInclude<ExtArgs> | null
  /**
   * Filter, which Task to fetch.
   */
  where: Prisma.TaskWhereUniqueInput
}

/**
 * Task findUniqueOrThrow
 */
export type TaskFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Task
   */
  select?: Prisma.TaskSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Task
   */
  omit?: Prisma.TaskOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TaskInclude<ExtArgs> | null
  /**
   * Filter, which Task to fetch.
   */
  where: Prisma.TaskWhereUniqueInput
}

/**
 * Task findFirst
 */
export type TaskFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Task
   */
  select?: Prisma.TaskSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Task
   */
  omit?: Prisma.TaskOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TaskInclude<ExtArgs> | null
  /**
   * Filter, which Task to fetch.
   */
  where?: Prisma.TaskWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Tasks to fetch.
   */
  orderBy?: Prisma.TaskOrderByWithRelationInput | Prisma.TaskOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Tasks.
   */
  cursor?: Prisma.TaskWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Tasks from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Tasks.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Tasks.
   */
  distinct?: Prisma.TaskScalarFieldEnum | Prisma.TaskScalarFieldEnum[]
}

/**
 * Task findFirstOrThrow
 */
export type TaskFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Task
   */
  select?: Prisma.TaskSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Task
   */
  omit?: Prisma.TaskOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TaskInclude<ExtArgs> | null
  /**
   * Filter, which Task to fetch.
   */
  where?: Prisma.TaskWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Tasks to fetch.
   */
  orderBy?: Prisma.TaskOrderByWithRelationInput | Prisma.TaskOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Tasks.
   */
  cursor?: Prisma.TaskWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Tasks from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Tasks.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Tasks.
   */
  distinct?: Prisma.TaskScalarFieldEnum | Prisma.TaskScalarFieldEnum[]
}

/**
 * Task findMany
 */
export type TaskFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Task
   */
  select?: Prisma.TaskSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Task
   */
  omit?: Prisma.TaskOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TaskInclude<ExtArgs> | null
  /**
   * Filter, which Tasks to fetch.
   */
  where?: Prisma.TaskWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Tasks to fetch.
   */
  orderBy?: Prisma.TaskOrderByWithRelationInput | Prisma.TaskOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Tasks.
   */
  cursor?: Prisma.TaskWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Tasks from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Tasks.
   */
  skip?: number
  distinct?: Prisma.TaskScalarFieldEnum | Prisma.TaskScalarFieldEnum[]
}

/**
 * Task create
 */
export type TaskCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Task
   */
  select?: Prisma.TaskSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Task
   */
  omit?: Prisma.TaskOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TaskInclude<ExtArgs> | null
  /**
   * The data needed to create a Task.
   */
  data: Prisma.XOR<Prisma.TaskCreateInput, Prisma.TaskUncheckedCreateInput>
}

/**
 * Task createMany
 */
export type TaskCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Tasks.
   */
  data: Prisma.TaskCreateManyInput | Prisma.TaskCreateManyInput[]
}

/**
 * Task createManyAndReturn
 */
export type TaskCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Task
   */
  select?: Prisma.TaskSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Task
   */
  omit?: Prisma.TaskOmit<ExtArgs> | null
  /**
   * The data used to create many Tasks.
   */
  data: Prisma.TaskCreateManyInput | Prisma.TaskCreateManyInput[]
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TaskIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * Task update
 */
export type TaskUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Task
   */
  select?: Prisma.TaskSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Task
   */
  omit?: Prisma.TaskOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TaskInclude<ExtArgs> | null
  /**
   * The data needed to update a Task.
   */
  data: Prisma.XOR<Prisma.TaskUpdateInput, Prisma.TaskUncheckedUpdateInput>
  /**
   * Choose, which Task to update.
   */
  where: Prisma.TaskWhereUniqueInput
}

/**
 * Task updateMany
 */
export type TaskUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Tasks.
   */
  data: Prisma.XOR<Prisma.TaskUpdateManyMutationInput, Prisma.TaskUncheckedUpdateManyInput>
  /**
   * Filter which Tasks to update
   */
  where?: Prisma.TaskWhereInput
  /**
   * Limit how many Tasks to update.
   */
  limit?: number
}

/**
 * Task updateManyAndReturn
 */
export type TaskUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Task
   */
  select?: Prisma.TaskSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Task
   */
  omit?: Prisma.TaskOmit<ExtArgs> | null
  /**
   * The data used to update Tasks.
   */
  data: Prisma.XOR<Prisma.TaskUpdateManyMutationInput, Prisma.TaskUncheckedUpdateManyInput>
  /**
   * Filter which Tasks to update
   */
  where?: Prisma.TaskWhereInput
  /**
   * Limit how many Tasks to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TaskIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * Task upsert
 */
export type TaskUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Task
   */
  select?: Prisma.TaskSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Task
   */
  omit?: Prisma.TaskOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TaskInclude<ExtArgs> | null
  /**
   * The filter to search for the Task to update in case it exists.
   */
  where: Prisma.TaskWhereUniqueInput
  /**
   * In case the Task found by the `where` argument doesn't exist, create a new Task with this data.
   */
  create: Prisma.XOR<Prisma.TaskCreateInput, Prisma.TaskUncheckedCreateInput>
  /**
   * In case the Task was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.TaskUpdateInput, Prisma.TaskUncheckedUpdateInput>
}

/**
 * Task delete
 */
export type TaskDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Task
   */
  select?: Prisma.TaskSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Task
   */
  omit?: Prisma.TaskOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TaskInclude<ExtArgs> | null
  /**
   * Filter which Task to delete.
   */
  where: Prisma.TaskWhereUniqueInput
}

/**
 * Task deleteMany
 */
export type TaskDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Tasks to delete
   */
  where?: Prisma.TaskWhereInput
  /**
   * Limit how many Tasks to delete.
   */
  limit?: number
}

/**
 * Task.subtasks
 */
export type Task$subtasksArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Subtask
   */
  select?: Prisma.SubtaskSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Subtask
   */
  omit?: Prisma.SubtaskOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SubtaskInclude<ExtArgs> | null
  where?: Prisma.SubtaskWhereInput
  orderBy?: Prisma.SubtaskOrderByWithRelationInput | Prisma.SubtaskOrderByWithRelationInput[]
  cursor?: Prisma.SubtaskWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.SubtaskScalarFieldEnum | Prisma.SubtaskScalarFieldEnum[]
}

/**
 * Task.reminders
 */
export type Task$remindersArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Reminder
   */
  select?: Prisma.ReminderSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Reminder
   */
  omit?: Prisma.ReminderOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ReminderInclude<ExtArgs> | null
  where?: Prisma.ReminderWhereInput
  orderBy?: Prisma.ReminderOrderByWithRelationInput | Prisma.ReminderOrderByWithRelationInput[]
  cursor?: Prisma.ReminderWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.ReminderScalarFieldEnum | Prisma.ReminderScalarFieldEnum[]
}

/**
 * Task.attachments
 */
export type Task$attachmentsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Attachment
   */
  select?: Prisma.AttachmentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Attachment
   */
  omit?: Prisma.AttachmentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AttachmentInclude<ExtArgs> | null
  where?: Prisma.AttachmentWhereInput
  orderBy?: Prisma.AttachmentOrderByWithRelationInput | Prisma.AttachmentOrderByWithRelationInput[]
  cursor?: Prisma.AttachmentWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.AttachmentScalarFieldEnum | Prisma.AttachmentScalarFieldEnum[]
}

/**
 * Task.taskLabels
 */
export type Task$taskLabelsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TaskLabel
   */
  select?: Prisma.TaskLabelSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TaskLabel
   */
  omit?: Prisma.TaskLabelOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TaskLabelInclude<ExtArgs> | null
  where?: Prisma.TaskLabelWhereInput
  orderBy?: Prisma.TaskLabelOrderByWithRelationInput | Prisma.TaskLabelOrderByWithRelationInput[]
  cursor?: Prisma.TaskLabelWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.TaskLabelScalarFieldEnum | Prisma.TaskLabelScalarFieldEnum[]
}

/**
 * Task without action
 */
export type TaskDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Task
   */
  select?: Prisma.TaskSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Task
   */
  omit?: Prisma.TaskOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TaskInclude<ExtArgs> | null
}
